### ISSUE TITLE
visitor count increases with each refresh

### ISSUE THREAD

**Issue by kambleaa007** [twindle-co/twindle#117]
for same ip it shoudnt increase more than once
#107 not working as expected

**Comment by mrsidverse** [comment]
Yeah, that's how it works.
This is counter of profile views (page hits), not a counter of unique visitors. There is no way to get the username, browser user agent or IP address of the visitor because GitHub proxies all image URLs through the GitHub Camo service. In other words, we can only increment the counter for each request from the GitHub proxy server, we don't know who initiated it.
So we have to ignore that, that's how everyone is using it.

**Comment by kambleaa007** [comment]
we can do get IP address, 

`http://ip-api.com/json?callback=?`

```
fetch('http://ip-api.com/json?callback=?', function(data) {
  console.log(JSON.stringify(data, null, 2));
});
```

**Comment by kambleaa007** [comment]
Lets close this issue if this problem not worth solving or time wasting

**Comment by johnjacobkenny** [comment]
Interesting! Does this refresh for all the forks too?

**Comment by arthurbuhl** [comment]
@johnjacobkenny Yes, it refreshes in forks too.

I also noticed, it refreshes in comments also. Just keep reloading this page w/ https://github.com/twindle-co/twindle/pull/107#issuecomment-708979715 to see the effect.

**Comment by johnjacobkenny** [comment]
Haha :rofl:

**Comment by johnjacobkenny** [comment]
I guess if anyone has a better idea to do it, maybe continue this issue, else we can close it :smile:
