### ISSUE TITLE
Resolving Your Merge Conflicts

### ISSUE THREAD

**Issue by nishanknavelkar** [twindle-co/twindle#263]
This is how I resolved my merge conflicts
1. Pull the changes from the orignal repo to your forked repo
2. Check for changes (VS code also provides a promt to resolve the conflict)
3. After solving the conflict, save and push the changes
4. Ask for review by reaching out on discord or twitter.

P.S: This is how I did it, fellow experts might add on to this.

**Comment by thunder-coding** [comment]
A very simple explanation of the very complex merge conflict solving
 👍👍

Must add to Wikis section

**Comment by thunder-coding** [comment]
Adding to Wikis, then you can close the issue

**Comment by thunder-coding** [comment]
https://github.com/twindle-co/twindle/wiki/Resolving-merge-conflicts

Any suggestions for improvements on this Wiki are most welcome

**Comment by tusharkandpal** [comment]
To be specific, main is the branch, you can replace word with "original" :)

**Comment by pranavgoel29** [comment]
Good and simple instructions 😄

**Comment by Akshay2996** [comment]
Great for the beginners to understand merge conflicts @nishanknavelkar 👍

**Comment by Akshay2996** [comment]
Hi everyone👋
Suggestion for improvement!!

Getting stuck with merge conflict

**Solve your merge conflict**

1. Clone your repository
2. Open in VSCode & Write the below command in git bash/terminal
- `git remote add upstream https//:url of the twindle repo/`
- `git fetch upstream`
- `git rebase upstream/main`

This will automatically update your repository if any new changes are made to the Twindle Repo because of the PR.

**Comment by nishanknavelkar** [comment]
Any further techniques for resolving merge issues can be updated at the wiki 
https://github.com/twindle-co/twindle/wiki/Resolving-merge-conflicts

Closing this issue. ✌
