### ISSUE TITLE
Video: Software Engineering is Overwhelming

### ISSUE THREAD

**Issue by johnjacobkenny** [twindle-co/twindle#420]
Here's a video I came across which resonates with me. This guy explains how software engineer looks complicated and confusing in the beginning, and how it is common for everyone to feel the same initially, and how to get to the stage of understanding it.

Two questions he mentions. For each tech you come across ask,
1. what is it
2. **why does it exist**

Break down big components into fundamentals. Everything can be broken into standards and fundamentals. Once you understand these you will see through all the marketing stuff and then everything will start to be simpler.

If you watch it, please share your takeaways as comments here.
https://www.youtube.com/watch?v=MbDjrztWtX4

If this is useful for many people, maybe add into resources section.

**Comment by sarathkumar6** [comment]
@johnjacobkenny I concur with you. The 5 whys is a blanket rule that could be applied any a problem of varied complexity. Instead of just bandwagoning, should ask why do we want to use a particular tech and what are we trying to achieve is important. 

Recently, big banking companies i.e., Bank Of America announced that they're building their db using NoSQL (MongoDB) to leverage the performance. NoSQL comes with its own trade-off i.e., data accuracy, integrity and duplication. Only time will tell if its a great move or just bandwagoning. I feel traditional SQL still has its place in the document based db

**Comment by proful** [comment]
@johnjacobkenny please move to docs section

**Comment by johnjacobkenny** [comment]
Done!
