### ISSUE TITLE
Improving Twitter API Integration Code - Javascript coding standards

### ISSUE THREAD

**Issue by Mira-Alf** [twindle-co/twindle#554]
### #Migrate to ES6? Necessary?
* Current code looks cluttered with require and module.exports syntax. Would it be better to use import and export keywords?
* How to test on node.js using the ES6 keywords - import and export? I am no JS expert. but arrow functions seems to work so only certain ES6 features dont work in NodeJS - 
* The above point can be of low priority but we need to establish some consistency in the code.
* I also plan to refactor some of the functions to ES6 arrow functions and the async/await call.

**Comment by arthurbuhl** [comment]
I am not sure if we should include ES6 and the async/await calls for this project at the moment, as this is a project for the beginners and most of them might not be familiar with some of the syntax & advanced concepts. Let's work with vanilla javascript for now and try to make the code work first for now. Once done we can work on incrementally updating the code to ES6 so that everyone can understand the changes and learn in the process.

Anyways, just wanted to share my views regarding this. I will leave the final decision to other members and contributors @twindle-co/developer 

Thanks.

**Comment by JoelVinayKumar** [comment]
But, I recommend mentoring on adhering to some coding standards. This will be very useful to the beginners. But, I'm worried it might discourage some to withdraw if they cannot cope

**Comment by proful** [comment]
Not needed now.
