### ISSUE TITLE
CLI epub Table of Content suggestions

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#749]
![image](https://user-images.githubusercontent.com/354596/98663380-20ad5480-239d-11eb-8e19-86db4017eec9.png)

Remove
1. - Table Of Contents -
2. Chapter 1

Update with (show 25-30 letter from tweets)
1.  This is also applicable for
2.  Of course, you can turn a

**Comment by tolgaerdonmez** [comment]
Out of my research on epub-gen's doc, I could only add chapters to Table of contents by adding chapters.
Then I rendered tweet by tweet and created a seperate chaptered epub. But because of the page breaks I think it is a bit annoying.


![First page](https://user-images.githubusercontent.com/45141388/98807784-3ae24380-242c-11eb-970f-e25cd30715fc.jpeg)

**Comment by proful** [comment]
Page breaks for each tweets doesn't seem good.

May be remove the contents

And add little text to chapter 1

**Comment by tolgaerdonmez** [comment]
If works, I'll add a custom contents page and add anchor links to navigate.

**Comment by tolgaerdonmez** [comment]
I see that epub-gen is also using anchor links, but from a reason I yet don't understand, the ids that I set to elements won't work. I created an issue to epub-gen's repository hope someone will help

**Comment by proful** [comment]
@johnjacobkenny for you to help when you get a chance

**Comment by tolgaerdonmez** [comment]
with the PR #787 this issue is no longer needed I suppose.
