### ISSUE TITLE
CLI Edge cases Not able to read thread properly

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#758]
https://twitter.com/b0rk/status/1326162989335064578

`node . -i 1326162989335064578`

**Comment by madhusudanbabar** [comment]
I'll try this.

**Comment by madhusudanbabar** [comment]
I'm facing some troubles now

I tried to create the thread manually and tested on my own thread
here is the link https://twitter.com/MadhusudanBabar/status/1326484312108249088
![Screenshot (117)](https://user-images.githubusercontent.com/28552728/98807192-4ccde180-2440-11eb-8d62-ca65f0e9a61c.png)

but I'm getting the error `TypeError: Cannot read property '0' of undefined`

can anyone confirm with this tweet id `1326484312108249088` and here is the url https://twitter.com/MadhusudanBabar/status/1326484312108249088

**Comment by proful** [comment]
@johnjacobkenny @PurUVJ @Mira-Alf can anyone help @madhusudanbabar

**Comment by PuruVJ** [comment]
> I'm facing some troubles now
> 
> I tried to create the thread manually and tested on my own thread
> here is the link https://twitter.com/MadhusudanBabar/status/1326484312108249088
> ![Screenshot (117)](https://user-images.githubusercontent.com/28552728/98807192-4ccde180-2440-11eb-8d62-ca65f0e9a61c.png)
> 
> but I'm getting the error `TypeError: Cannot read property '0' of undefined`
> 
> can anyone confirm with this tweet id `1326484312108249088` or here is the URL https://twitter.com/MadhusudanBabar/status/1326484312108249088
> 
> none of these ID's is working
> `1326484308014534656`, `1326484312108249088`, `1326484310052966401` and if I go with the puppeteer option then there's another error
> ![Screenshot (119)](https://user-images.githubusercontent.com/28552728/98808368-ffeb0a80-2441-11eb-8f23-827dbd4b8dd2.png)

These issues are happening b'coz there's a deleted tweet there. haven't tested for those yet.

**Comment by proful** [comment]
@madhusudanbabar can you please check this if it is deleted tweets skip that specific tweet.

**Comment by madhusudanbabar** [comment]
> @madhusudanbabar can you please check this if it is deleted tweets skip that specific tweet.

Just one tweet from that thread was deleted, 

But when i visit with the URL this tweet is available, the IDs posted are not deleted, i deleted different one

You can verify with 
twitter.com/MadhusudanBabar/status/id

**Comment by madhusudanbabar** [comment]
this is not a proper solution but I found another way to get it, by means of the referenced tweet's id from the `expansions` and then getting the contents of that tweet id and repeating the same process until there are no referenced tweets, but this actually goes in reverse order, means we need to check for the id of the last tweet and from that, we traverse back to the first tweet.
![twindle_tweets](https://user-images.githubusercontent.com/28552728/98903892-79383b00-24de-11eb-9e6f-29b029fa2323.png)

**Comment by proful** [comment]
Very good analysis @madhusudanbabar

@PuruVJ and @Mira-Alf any comments?

**Comment by Mira-Alf** [comment]
I studied this issue really hard. Here is the problem explained in my words
* This thread contains the main thread(first thread followed by 7 tweets on the same thread)
* However after creating the thread, this user has added a reply to the first tweet which is also added to the same conversation and shares the conversation_id(done later not at the time of creating the thread)
* When I construct a thread of tweets in the code, I look at direct replies to the first tweet and then replies to that tweet and so on. This is done to avoid adding replies, but the problem is the first tweet in this thread now has two distinct replies and in my case picks up the second reply and fails to build the original thread. 
* I am trying to fix it in the code. But any ideas for this I will truly appreciate. @johnjacobkenny or @PuruVJ please help!!

## First Tweet of the thread
![image](https://user-images.githubusercontent.com/64691316/99259504-1f1dd980-2840-11eb-8fd8-3f23751baaef.png)
## Direct Reply 1
![image](https://user-images.githubusercontent.com/64691316/99259568-35c43080-2840-11eb-82f7-26691fb1aa72.png)
## Direct Reply 2
![image](https://user-images.githubusercontent.com/64691316/99259615-4674a680-2840-11eb-8659-5af71e85d507.png)

**Comment by johnjacobkenny** [comment]
Is there a way for you to filter the first level or replies based on time? Will it work if we pick the older first reply?

**Comment by PuruVJ** [comment]
@Mira-Alf is this issue fixed?

**Comment by PuruVJ** [comment]
This is worth while, but not focusing on this for some time
