### ISSUE TITLE
CLI HackerNews integration

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#824]
https://github.com/HackerNews/API

[![tutorial](https://img.youtube.com/vi/kX4ejOw46Vg/0.jpg)](https://www.youtube.com/watch?v=kX4ejOw46Vg).

**Comment by tolgaerdonmez** [comment]
What's the aim of this ?

**Comment by proful** [comment]
@tr0mbl3y update?

**Comment by tr0mbl3y** [comment]
![Screenshot from 2020-11-29 19-43-45](https://user-images.githubusercontent.com/72851843/100544383-47172f00-327b-11eb-8683-26f4a9174a1b.png)

The pdf looks clean but in few places handlebars is unable to resolve the unicode  characters  and html tags in the stories comments like the pic below 

![Screenshot from 2020-11-29 19-27-44](https://user-images.githubusercontent.com/72851843/100544467-d02e6600-327b-11eb-8056-6c76d19d3955.png)

-right now i am able to fetch 20 stories with 20 comments each on the particular keyword that user provide -these are latest comments which are made on particular stories

work to do:
-i am working on how to make hierarchy of every comment whether its old or new so that all comment are displayed in a hierarchical order on the pdf for every story
-the pdf needs finishing too

**Comment by proful** [comment]
Create a pr

**Comment by Mira-Alf** [comment]
We have a fully functioning module for hackernews. I am closing this issue for now.
