### ISSUE TITLE
Modularize Handle bar Templates

### ISSUE THREAD

**Issue by proful** [twindle-co/twindle#858]
https://handlebarsjs.com/guide/partials.html#basic-partials
https://blog.teamtreehouse.com/handlebars-js-part-2-partials-and-helpers

Can we explore Partials?

**Comment by PuruVJ** [comment]
I and @Mira-Alf looked into it and we both agreed: Bad Idea.

Partials are horribly complicated and wouldn't solve any problem, rather create new ones.

Mira partially solved the page break problem using a CSS property. It can't be completely solved without imposing some restrictions on image sizes and embedded tweet sizes or so. **Big enough entities will break.**

@tolgaerdonmez is working on replacing handlebars templates with svelte SSR'd components. These components will be agnostic, and can be composed easily and flexibly for both EPUB and PDF code. Thanks to Svelte, we'd be able to develop and design the templates just like we do web development: Running a dev server.

We have both looked into pdfkit and we don't think we are capable of writing scalable, future-proof, and overall capable-enough implementation. Here's why:
- Working with pdfkit is like working with the `Canvas` API. It prioritizes **drawing** objects on the pages rather than. You have to calculate and assign manual coordinates to every single thing. That alone makes it highly unfavorable.
- For the above purposes, we'd need to do lot of calculations for every single thing. Make our own `Text`, `Image`, components, and these are highly likely to be very inflexible
- Chances are very high that the code outcome would be tightly coupled with the template components, and if I and Tolga leave this project, any customization would be nearly impossible and would require a lot of professional touch
- Doing this will take time. Way too much time. We'd rather add more features and shoot more bugs with the CLI itself rather than re-invent the wheel.

Tolga and I discussed about Puppeteer on AWS Lambda. We think it is feasible.
- I have done a project before that compiled Handlebars and printed a huge 30 page document using puppeteer on Firebase Functions, and implemented all the wild optimization methods.
- We found some resources which download chromium once and cache it on AWS itself efficiently (AWS Lambda, if it's similar to Cloud Functions, doesn't charge on node_modules size. Not sure on this point. Research required). 
- Combined with the global variables hack, we should be able to minimise costs by reusing the same chromium instances when traffic is too high.

**Comment by PuruVJ** [comment]
cc @johnjacobkenny

**Comment by Mira-Alf** [comment]
I am okay with sveltejs as long as it doesnt cause any new issues and everyone is onboard with the idea. Like @PuruVJ mentioned, handlebars doesnt solve all the formatting issues - I just solved the pagebreak issue but even that some of the linkboxes still cause some issues. And newer issues might crop up for github and hackernews formats as well. If sveltejs is AWS lambda compatible then I am all for it.

**Comment by johnjacobkenny** [comment]
I'll have to catch up with these!!

**Comment by tolgaerdonmez** [comment]
I also agree with @PuruVJ about handlebars to svelte transition. It would be much better to handle things in a more code splitted, more controllable with bare js logic and such. 👍👍👍

**Comment by PuruVJ** [comment]
I suppose this can be closed as Mira has introduced Partials and we have agreed on Svelte as an experiment.
