### ISSUE TITLE
twindle-cli runtime error

### ISSUE THREAD

**Issue by harshulvijay** [twindle-co/twindle#946]
Command used:
```bash
node . -i 1337875532483092480 -o test
```

![image](https://user-images.githubusercontent.com/64775657/102520179-6aced780-40b9-11eb-91be-86efc3270875.png)

**Comment by PuruVJ** [comment]
This is the result of my attempt to merge stuff from `renderer-svelte` to `main`

**Comment by Mira-Alf** [comment]
Sure, I will take a look at this.

**Comment by Mira-Alf** [comment]
This is not an issue because of the svelte changes. This is a unique error happening in a special circumstance. We need to discuss on how to handle this.
Here is the tweet id: [Tweet link](https://twitter.com/lavie_encode/status/1337875532483092480)

* The tweet is a reply to another user and consequently not the first tweet of the thread
* Code tries to locate the first tweet of the thread but the first tweet has not been made by the same user - consequently it returns undefined
* Since the lookup fails - it is unable to find/search other tweets on the same thread
* What should be done in this case? ThreadReader app simply states this is a reply and cannot be rolled. Should we take a similar approach or tweak the logic to print the original post and the reply?

**Comment by PuruVJ** [comment]
> ThreadReader app simply states this is a reply and cannot be rolled. Should we take a similar approach or tweak the logic to print the original post and the reply?

The second part seems good enough.

Did you try some other tweet?

**Comment by proful** [comment]
@all-contributors please add @Mira-Alf  for code, mentoring

**Comment by proful** [comment]
@all-contributors please add @tolgaerdonmez   for code, mentoring

**Comment by PuruVJ** [comment]
Making this another issue for now.
