### ISSUE TITLE
Readability issues

### ISSUE THREAD

**Issue by tr0mbl3y** [twindle-co/twindle#953]
1. unable to render images such as graphs
2. need to do something about handling slides in websites
3. in some case unable to render full contents from websites
![Screenshot from 2020-12-19 11-08-32](https://user-images.githubusercontent.com/72851843/102681862-f3996080-41ea-11eb-90c2-d27cd6ae4b77.png)  :case 3

![Screenshot from 2020-12-19 10-56-43](https://user-images.githubusercontent.com/72851843/102681887-22afd200-41eb-11eb-82c2-541bef22d2e2.png) :case 1

![Screenshot from 2020-12-19 10-50-13](https://user-images.githubusercontent.com/72851843/102681901-36f3cf00-41eb-11eb-9be3-43e9974b27b5.png) : case 2

websites i tried on:
https://www.nytimes.com/interactive/2020/health/moderna-covid-19-vaccine.html : case 1
https://www.wsj.com/articles/tech-giants-face-new-rules-in-europe-backed-by-huge-fines-11608046500 : case 3
https://www.nytimes.com/live/2020/12/18/world/covid-19-coronavirus  : case 2

linkin' with other issues related to redability #949

**Comment by proful** [comment]
@all-contributors please add @tr0mbl3y  for code

**Comment by Mira-Alf** [comment]
@tr0mbl3y the problem is that the Mozilla reader view renders the above websites the same way which is what we use, so our output looks exactly the same way. If we need to fix this, we need to look at their source code to fix what they are doing or use a different application underneath. If anyone else has any other ideas, we can try it out

**Comment by tr0mbl3y** [comment]
@Mira-Alf alright then this is not an issue anymore! but do check  for case 3:  like in first picture i am not getting full contents

**Comment by Mira-Alf** [comment]
@tr0mbl3y these are some interesting cases. Case 3 happened because the content is hidden behind a paywall. Cases 1 and 2 are a little strange but the Mozilla reader renders the content this way as well and they use the @mozilla-readability npm module. So there will need to be either tweaks for these kind of cases or we must use a different npm module altogether. I think we can close this issue for now.

**Comment by tr0mbl3y** [comment]
alright closing this then!
